backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow
media_folder: "static/img/uploads"
public_folder: "/img/uploads"
display_url: https://docusaurus-lansolo99-test.netlify.app
editor:
  preview: false
collections:
  - name: "docs" # Used in routes, e.g., /admin/collections/docs
    label: "Docs" # Used in the UI
    label_singular: "doc"
    description: "Arborescence composant la documentation principale"
    folder: "docs" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - label: "Description"
        name: "description"
        widget: "string"
        pattern: [".{20,}", "At least20 chars"]
        comment: "SEO Description"
      - { label: "Sidebar Label", name: "sidebar_label", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
